Improvements

diff --git a/SOURCES/mkcryptpasswd b/SOURCES/mkcryptpasswd
--- a/SOURCES/mkcryptpasswd
+++ b/SOURCES/mkcryptpasswd
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 APP="MkCryptPasswd"
-VER="1.6.1"
+VER="1.6.2"
 
 ###############################################################################
 
@@ -10,48 +10,31 @@ BOLD=1
 UNLN=4
 RED=31
 GREEN=32
-BROWN=33
+YELLOW=33
 BLUE=34
 MAG=35
 CYAN=36
 GREY=37
 DARK=90
 
-CL_NORM="\e[${NORM}m"
-CL_BOLD="\e[${BOLD}m"
-CL_UNLN="\e[${UNLN}m"
-CL_RED="\e[${RED}m"
-CL_GREEN="\e[${GREEN}m"
-CL_BROWN="\e[${BROWN}m"
-CL_BLUE="\e[${BLUE}m"
-CL_MAG="\e[${MAG}m"
-CL_CYAN="\e[${CYAN}m"
-CL_GREY="\e[${GREY}m"
-CL_DARK="\e[${DARK}m"
-CL_BL_RED="\e[${RED};1m"
-CL_BL_GREEN="\e[${GREEN};1m"
-CL_BL_BROWN="\e[${BROWN};1m"
-CL_BL_BLUE="\e[${BLUE};1m"
-CL_BL_MAG="\e[${MAG};1m"
-CL_BL_CYAN="\e[${CYAN};1m"
-CL_BL_GREY="\e[${GREY};1m"
-CL_BL_DARK="\e[${DARK};1m"
-CL_UL_RED="\e[${RED};4m"
-CL_UL_GREEN="\e[${GREEN};4m"
-CL_UL_BROWN="\e[${BROWN};4m"
-CL_UL_BLUE="\e[${BLUE};4m"
-CL_UL_MAG="\e[${MAG};4m"
-CL_UL_CYAN="\e[${CYAN};4m"
-CL_UL_GREY="\e[${GREY};4m"
-CL_UL_DARK="\e[${DARK};4m"
-CL_BG_RED="\e[${RED};7m"
-CL_BG_GREEN="\e[${GREEN};7m"
-CL_BG_BROWN="\e[${BROWN};7m"
-CL_BG_BLUE="\e[${BLUE};7m"
-CL_BG_MAG="\e[${MAG};7m"
-CL_BG_CYAN="\e[${CYAN};7m"
-CL_BG_GREY="\e[${GREY};7m"
-CL_BG_DARK="\e[${DARK};7m"
+CL_NORM="\e[0m"
+CL_BOLD="\e[0;${BOLD};49m"
+CL_UNLN="\e[0;${UNLN};49m"
+CL_RED="\e[0;${RED};49m"
+CL_GREEN="\e[0;${GREEN};49m"
+CL_YELLOW="\e[0;${YELLOW};49m"
+CL_BLUE="\e[0;${BLUE};49m"
+CL_MAG="\e[0;${MAG};49m"
+CL_CYAN="\e[0;${CYAN};49m"
+CL_GREY="\e[0;${GREY};49m"
+CL_DARK="\e[0;${DARK};49m"
+CL_BL_RED="\e[1;${RED};49m"
+CL_BL_GREEN="\e[1;${GREEN};49m"
+CL_BL_YELLOW="\e[1;${YELLOW};49m"
+CL_BL_BLUE="\e[1;${BLUE};49m"
+CL_BL_MAG="\e[1;${MAG};49m"
+CL_BL_CYAN="\e[1;${CYAN};49m"
+CL_BL_GREY="\e[1;${GREY};49m"
 
 ###############################################################################
 
@@ -73,11 +56,9 @@ salt_length=8
 
 main() {
   if [[ ! -t 1 || -n "$no_colors" ]] ; then
-    unset NORM BOLD UNLN RED GREEN BROWN BLUE MAG CYAN GREY DARK
-    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_BROWN CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
-    unset CL_BL_RED CL_BL_GREEN CL_BL_BROWN CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
-    unset CL_UL_RED CL_UL_GREEN CL_UL_BROWN CL_UL_BLUE CL_UL_MAG CL_UL_CYAN CL_UL_GREY CL_UL_DARK
-    unset CL_BG_RED CL_BG_GREEN CL_BG_BROWN CL_BG_BLUE CL_BG_MAG CL_BG_CYAN CL_BG_GREY CL_BG_DARK
+    unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
+    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
+    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
   fi
 
   if [[ -n "$help" || -n "$usage" ]] ; then
@@ -91,7 +72,7 @@ main() {
   fi
 
   if ! checkDeps "python" "mktemp" "cracklib-check" ; then
-    show "Error! For using this utility you must install python, cracklib-check and mktemp." $RED
+    error "Error! For using this utility you must install python, cracklib-check and mktemp." $RED
     exit 1
   fi
 
@@ -117,7 +98,7 @@ calculate() {
     password=$(cat /dev/stdin)
 
     if [[ -z "$password" ]] ; then
-      show "Password can't be empty!" $RED
+      error "Password can't be empty!" $RED
       exit 1
     fi
 
@@ -139,7 +120,9 @@ calculate() {
       clnPassInput ${#password}
 
       if [[ -z "$password" ]] ; then
-        show "\nPassword can't be empty!\n" $BROWN
+        show ""
+        error "Password can't be empty!" $YELLOW
+        show ""
         continue
       fi
 
@@ -173,7 +156,7 @@ isWellPassword() {
 
   if [[ "$password_info" != "OK" ]] ; then
     if [[ -z "$stdin" ]] ; then
-      show "\nPassword is too weak: $password_info\n" $BROWN
+      show "\nPassword is too weak: $password_info\n" $YELLOW
     fi
 
     return 1
@@ -219,8 +202,12 @@ show() {
   fi
 }
 
+error() {
+  show "$@" 1>&2
+}
+
 showArgWarn() {
-  show "Error! You used unsupported argument $1. Please check command syntax." $RED
+  error "Error! You used unsupported argument $1. Please check command syntax." $RED
   exit 1
 }
 
