Improvements

diff --git a/SOURCES/mkcryptpasswd b/SOURCES/mkcryptpasswd
--- a/SOURCES/mkcryptpasswd
+++ b/SOURCES/mkcryptpasswd
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC1117,SC2034,SC2154
 
+########################################################################################
+
+if [[ -n "${SCRIPT_DEBUG}" ]] ; then
+  set -x
+fi
+
+########################################################################################
+
 APP="MkCryptPasswd"
-VER="1.7.1"
+VER="1.7.2"
 
 ###############################################################################
 
@@ -56,6 +64,8 @@ salt_length=8
 ###############################################################################
 
 main() {
+  trap errHandler ERR
+
   if [[ ! -t 1 || -n "$no_colors" ]] ; then
     unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
     unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
@@ -218,11 +228,6 @@ error() {
   show "$@" 1>&2
 }
 
-showArgWarn() {
-  error "Error! You used unsupported argument $1. Please check command syntax." $RED
-  exit 1
-}
-
 usage() {
   show ""
   show "${CL_BOLD}Usage:${CL_NORM} mkcryptpasswd ${CL_GREEN}{option}${CL_NORM}"
@@ -260,6 +265,23 @@ about() {
   show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
   show "Essential Kaos Open Source License <https://essentialkaos.com/ekol>" $DARK
   show ""
+}
+
+showArgWarn() {
+  error "Error! You used unsupported argument $1. Please check command syntax." $RED
+  exit 1
+}
+
+# Handler for errors
+#
+# Code: No
+# Echo: No
+errHandler() {
+  while caller $((n++)) ; do
+    true
+  done
+
+  exit 1
 }
 
 ## ARGUMENTS PARSING 4 #################################################################
